force-app/main/default/objects/Insurance_Customer__c/Insurance_Customer__c.object-meta.xml
<CustomObject>
    <label>Insurance Customer</label>
    <nameField>
        <label>Insurance Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_PolicyHolder__c/Insurance_PolicyHolder__c.object-meta.xml
<CustomObject>
    <label>Insurance PolicyHolder</label>
    <nameField>
        <label>Insurance PolicyHolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance PolicyHolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_PolicyHolder__c/fields/Insurance_Customer__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Customer</label>
    <referenceTo>Insurance_Customer__c</referenceTo>
    <relationshipLabel>Insurance PolicyHolders</relationshipLabel>
    <relationshipName>Insurance_PolicyHolders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EinsteinInsuranceBotPolicyServiceTest.cls
@isTest
public with sharing class EinsteinInsuranceBotPolicyServiceTest {

@isTest
    private static void testWithValidPolicy(){
        
        List<Insurance_Customer__c> req = EinsteinInsuranceBotTestingUtil.createTestInsuranceCustomer();
       
        Test.startTest();
           
        List<Insurance_PolicyHolder__c> result = EinsteinInsuranceBotPolicyService.createCustomerPolicyData(req);
        
        System.assertEquals(1, result.size(), 'Expected case creation for customer query');
        
        Test.stopTest();
    }

}