force-app/main/default/objects/Insurance_Customer__c/Insurance_Customer__c.object-meta.xml
<CustomObject>
    <label>Insurance Customer</label>
    <nameField>
        <label>Insurance Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Customer__c/fields/Insurance_Type__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Type__c</fullName>
    <label>Insurance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Overseas Travel</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_PolicyHolder__c/Insurance_PolicyHolder__c.object-meta.xml
<CustomObject>
    <label>Insurance PolicyHolder</label>
    <nameField>
        <label>Insurance PolicyHolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance PolicyHolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_PolicyHolder__c/fields/Insurance_Customer__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Customer</label>
    <referenceTo>Insurance_Customer__c</referenceTo>
    <relationshipLabel>Insurance PolicyHolders</relationshipLabel>
    <relationshipName>Insurance_PolicyHolders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EinsteinInsuranceBotTestingUtil.cls
@isTest
public with sharing class EinsteinInsuranceBotTestingUtil {
 
    
    public static List<Insurance_Customer__c> createTestInsuranceCustomer(){
        List<Insurance_Customer__c> results = new List<Insurance_Customer__c>();
 
        Insurance_Customer__c c = new Insurance_Customer__c();
            c.Insurance_Type__c = 'Car';
            c.Customer_Name__c = 'Test User';
            
        results.add(c);
        
        insert results;
        return results;
    }
    
     public static List<Insurance_PolicyHolder__c> createTestInsuranceCustomerWithPolicy(){
     
         List<Insurance_PolicyHolder__c> results = new List<Insurance_PolicyHolder__c>();
            
         List<Insurance_Customer__c> c = EinsteinInsuranceBotTestingUtil.createTestInsuranceCustomer();
 
         Insurance_PolicyHolder__c i = new Insurance_PolicyHolder__c();
            i.Insurance_Customer__c = c.get(0).Id;
         
         results.add(i);
        
         insert results;
        return results;
    }   
}