force-app/main/default/objects/Insurance_Customer__c/Insurance_Customer__c.object-meta.xml
<CustomObject>
    <label>Insurance Customer</label>
    <nameField>
        <label>Insurance Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_PolicyHolder__c/Insurance_PolicyHolder__c.object-meta.xml
<CustomObject>
    <label>Insurance PolicyHolder</label>
    <nameField>
        <label>Insurance PolicyHolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance PolicyHolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_PolicyHolder__c/fields/Insurance_Customer__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Customer</label>
    <referenceTo>Insurance_Customer__c</referenceTo>
    <relationshipLabel>Insurance PolicyHolders</relationshipLabel>
    <relationshipName>Insurance_PolicyHolders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EinsteinInsuranceBotPolicyService.cls
public with sharing class EinsteinInsuranceBotPolicyService {

 
    @InvocableMethod(label='Insurance Bot Create Policy' description='Create a policy for a customer')
    public static List<Insurance_PolicyHolder__c> createCustomerPolicyData(List<Insurance_Customer__c> reqs) {
    
        Insurance_Customer__c req = reqs.get(0);

        if(req == null) { return null; }
        
        // Check if the user has create access on the Insurance_PolicyHolder__c fields
       if (!Schema.sObjectType.Insurance_PolicyHolder__c.fields.Insurance_Customer__c.isCreateable()) {
          // Returning null, error handling is done in the UI side of it
          return null;
       }
        
        Insurance_PolicyHolder__c policyObj = new Insurance_PolicyHolder__c();
        policyObj.Insurance_Customer__c = req.Id;
        
        insert policyObj;
        
        return new List<Insurance_PolicyHolder__c>{policyObj};
    }

}