force-app/main/default/objects/Insurance_PolicyHolder__c/Insurance_PolicyHolder__c.object-meta.xml
<CustomObject>
    <label>Insurance PolicyHolder</label>
    <nameField>
        <label>Insurance PolicyHolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance PolicyHolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_PolicyHolder__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EinsteinInsuranceBotPolicyLookup.cls
public with sharing class EinsteinInsuranceBotPolicyLookup {
    
    @InvocableMethod(label='Insurance Bot Get Valid Insurance Policy Number' description='Returns whether a policy number is valid or not')
    public static List<Boolean> isValidPolicyNumber(List<String> policyNumber) {
    
       // Check if the user has read access on the Insurance_PolicyHolder__c field
        if (!Schema.sObjectType.Insurance_PolicyHolder__c.fields.Id.isAccessible()) {
           // Returning null, error handling is done in the UI side of it
          return null;
        }

        List<Insurance_PolicyHolder__c> policy = [select Id,Policy_Number__c
                                              from Insurance_PolicyHolder__c
                                              where Policy_Number__c = :policyNumber
                                              ];
        
      
        if(policy != null && policy.size() == 1) {
            return new List<Boolean> {true};
        }
        
        return new List<Boolean> {false};
    }
}